sudo: required
services:
  - docker

before_install:
  - docker build -t yevhenlodovyi/fibonacci-test -f client/Dockerfile.dev client
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source ${HOME}/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json

script:
  - docker run yevhenlodovyi/fibonacci-test npm test -- --coverage

after_success:
  - docker build -t yevhenlodovyi/fibonacci-client client
  - docker build -t yevhenlodovyi/fibonacci-nginx nginx
  - docker build -t yevhenlodovyi/fibonacci-server server
  - docker build -t yevhenlodovyi/fibonacci-worker worker
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_ID}" --password-stdin
  - docker push yevhenlodovyi/fibonacci-client
  - docker push yevhenlodovyi/fibonacci-nginx
  - docker push yevhenlodovyi/fibonacci-server
  - docker push yevhenlodovyi/fibonacci-worker
