sudo: required
services:
  - docker
env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - DEPLOY_TO_GKE='false'
before_install:
  - docker build -t yevhenlodovyi/fibonacci-test -f client/Dockerfile.dev client
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_ID}" --password-stdin
  - |
    if [[ "${DEPLOY_TO_GKE}" == 'true' ]]; then
        openssl aes-256-cbc -K $encrypted_d9702aa4dcc8_key -iv $encrypted_d9702aa4dcc8_iv -in service-account.json.enc -out service-account.json -d
        curl https://sdk.cloud.google.com | bash > /dev/null
        source ${HOME}/google-cloud-sdk/path.bash.inc
        gcloud components update kubectl
        gcloud auth activate-service-account --key-file service-account.json
        gcloud config set project fibonacci-267912
        gcloud config set compute/zone us-central1-a
        gcloud container clusters get-credentials standard-cluster-1
    fi

script:
  - bash -c 'shopt -s globstar nullglob; shellcheck **/*.{sh,ksh,bash}'
  - docker run yevhenlodovyi/fibonacci-test npm test -- --coverage

deploy:
  - provider: script
    script: bash deploy-k8s.sh --publish
    on:
      branch: master
      condition: $DEPLOY_TO_GKE = false
  - provider: script
    script: bash deploy-k8s.sh --publish --deploy
    on:
      branch: master
      condition: $DEPLOY_TO_GKE = true
